# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'self-destructing-messagesChatApp' do
  pod 'Firebase', '~> 2.4.1'
end

target 'self-destructing-messagesChatAppTests' do

end

target 'self-destructing-messagesChatAppUITests' do

end

